### ISSUE TITLE
Make Class Based (Generic) Views

### ISSUE THREAD

**Issue by omkar-dsd** [omkar-dsd/MovieTracker#1]
_**MovieTracker/MovieTracker/tracker/views.py**_

Make this view Class-Based. Make request after proper testing.

**Comment by ShivangiSingh17** [comment]
let me try?

**Comment by omkar-dsd** [comment]
@Starcode71Ooze go ahead. Make sure u test it well before generating the PR.

**Comment by ralphleyga** [comment]
@Starcode71Ooze I'll fix this.
